# Generated by Django 5.0.2 on 2024-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('marca', models.CharField(max_length=64)),
                ('veiculo', models.CharField(max_length=64)),
                ('km_troca_oleo', models.PositiveIntegerField()),
            ],
        ),
    ]
