# Generated by Django 5.0.2 on 2024-04-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Motoristas', '0001_initial'),
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('hora_saida', models.TimeField()),
                ('km_saida', models.PositiveIntegerField()),
                ('destino', models.CharField(max_length=128)),
                ('data_retorno', models.DateField()),
                ('hora_retorno', models.TimeField()),
                ('km_retorno', models.IntegerField()),
                ('km_percorrido', models.IntegerField()),
                ('motorista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Motoristas.motorista')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Veiculos.veiculo')),
            ],
        ),
    ]
