# Generated by Django 5.0.2 on 2024-04-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0001_initial'),
        ('Motoristas', '0001_initial'),
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='controle',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='controle',
            name='motorista',
            field=models.ManyToManyField(to='Motoristas.motorista'),
        ),
        migrations.AddField(
            model_name='controle',
            name='veiculo',
            field=models.ManyToManyField(to='Veiculos.veiculo'),
        ),
    ]
