# Generated by Django 5.0.2 on 2024-04-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0002_remove_controle_motorista_remove_controle_veiculo_and_more'),
        ('Motoristas', '0001_initial'),
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='controle',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='controle',
            name='motorista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='Motoristas.motorista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controle',
            name='veiculo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='Veiculos.veiculo'),
            preserve_default=False,
        ),
    ]
