# Generated by Django 5.0.2 on 2024-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_motorista', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=18)),
                ('cnh', models.CharField(max_length=18)),
            ],
        ),
    ]
